kind: pipeline
name: klass-subsets-web

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn install
    when:
      event:
        - pull_request
        - push

  - name: test
    image: node:current-alpine
    commands:
      - yarn test
    when:
      event:
        - pull_request
        - push
    depends_on:
      - install

  - name: build
    image: node:current-alpine
    commands:
      - CI=false yarn run build
    when:
      event:
        - pull_request
        - push
    depends_on:
      - install

  - name: publish-docker
    image: plugins/gcr
    settings:
      repo: prod-bip/subsets-client
      registry: eu.gcr.io
      tags: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
      json_key:
        from_secret: gcr_credentials
    when:
      branch:
        - development
      event:
        - push
    depends_on:
      - test
      - build

---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
