kind: pipeline
name: klass-subsets-web

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn install
    when:
      event:
        - pull_request
        - push

  - name: test
    image: node:current-alpine
    commands:
      - yarn test
    when:
      event:
        - pull_request
        - push
    depends_on:
      - install

  - name: build
    image: node:current-alpine
    commands:
      - CI=false yarn run build
    when:
      event:
        - pull_request
        - push
    depends_on:
      - install

