name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - 'master'
  tags:
    include:
      - '*'
pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.32
#      ref: react-complete-tag-for-production
      endpoint: statisticsnorway (2)


variables:
  - group: Hemmeligheter
  - name: 'appName'
    value: 'subsets-client'
  - name: 'namespace'
    value: 'klass'
  - name: 'imageTag'
    value: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
  - name: 'sonarCloud'
    value: 'bipSonarCloud-Klass'
  - name: 'sourceVersion'
    value: '$(Build.SourceVersion)'



jobs:
  - template: javascript/react-complete-build.yml@templates
    parameters:
      appName: $(appName)
      imageTag: $(imageTag)
      namespace: $(namespace)
      sonarCloud: $(sonarCloud)
      tagToTag: $(sourceVersion)
